name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  codeql:
    name: "CodeQL Check"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  test:
    needs: [build, codeql]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: "${{ secrets.GH_PAT }}"
          template_repo: "oss-template"
          org: "devnw"
          sync_repo: "devnw/shared"
          sync_file: "sync.yml"
  pre-release:
    name: "Pre Release"
    if: github.event_name != 'pull_request'
    runs-on: "ubuntu-latest"
    needs: [build, codeql, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Build"
